version: 1
formatters:
  simple:
    format: '%(asctime)s %(levelname)s: %(message)s [in %(pathname)s:%(lineno)d]'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple
    level: INFO
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: simple
    level: INFO
    filename: app.log
root:
  level: INFO
  handlers: [console, file]
 